### ISSUE TITLE
Bootstrapping issues

### ISSUE THREAD

**Issue by azizshamim** [frymanio/mac_me#2]
Just a laundry list. will reorg into something useful:

> script/bootstrap: line 15: _has_ruby: command not foundscript/bootstrap: line 15: _has_ruby: command not found

**FIXED**: killed that whole section in `script/bootstrap` that doesn't really do anything.

> A new Hex version is available (0.11.1), please update with `mix local.hex`

**FIXED** `mix local.hex`

> warning: the dependency bunt requires Elixir "~> 1.1" but you are running on v1.0.4

**FIXED** `brew upgrade elixir`

> warning: the dependency exrm requires Elixir "~> 1.0.5" but you are running on v1.0.4

@jfryman - do we need `exrm` right now?

> WARN:  Missing plugins: [rebar3_hex]

probably tied to :point_up_2:

**Comment by jfryman** [comment]
New steps:

```
git clone https://github.com/frymanio/mac_me
cd mac_me
vagrant up
script/cibuild
```
